const List<String> sessionActivitiesList = [
  "Academic One to One",
  "Advocating on beneficiary's behalf",
  "Befriending",
  "Better off calculation",
  "Brexit Support",
  "Budgeting",
  "Case discussion",
  "Case research",
  "Character education session",
  "Christmas party",
  "Cultural Visit",
  "Discounted travel",
  "Distributing Food",
  "Drama",
  "ESOL Saturdays",
  "ESOL Whatsapp chats",
  "ESOL class",
  "Email contact",
  "Emotional Intelligence Session",
  "English conversation",
  "Event",
  "Exhibition",
  "Film",
  "Finance (identify income and outgoing)",
  "Finance assessment (assess if have debts, priority debts and non-priority debts)",
  "Flipgrid",
  "Form Filling",
  "Free employment provision",
  "Free health care provision",
  "Free school meals application",
  "Group",
  "Homework support",
  "Housing",
  "IT",
  "Impromptu meeting",
  "Information, Advice and Guidance",
  "Internship",
  "Interpreting / Translating",
  "Into School mentoring",
  "Into School programme",
  "Issue food bank voucher",
  "Laptop Loan",
  "Legacy benefits",
  "Liaise with GP",
  "Managing family funds",
  "Massage session",
  "Mathletics",
  "Meeting Representation",
  "Money Champions",
  "Moved to one to one support",
  "New Referral Sign Up",
  "No recourse to public fund",
  "Nutritional Workshop",
  "One to one",
  "PE",
  "Party",
  "Phone call",
  "Referrals & liaison to other agencies",
  "Refugee Week Celebration",
  "Renewal of ID for Welfare purpose",
  "Riding lesson",
  "SMS and Whatsapp Messaging",
  "Saturday cookery class",
  "Schemes, grants and social funds",
  "School trip",
  "Self-Confidence Workshop",
  "Stress and time management",
  "Theatre",
  "Third party referral of Beneficiary with NRPF",
  "Trip",
  "Universal credit",
  "University application / personal statement support",
  "Video call",
  "Volunteer one to one support",
  "Volunteering",
  "Walk in local \"Food bank\" collection",
  "Welfare & Benefit Online application",
  "Wellbeing check in",
  "Winter Clothing Donation",
  "Women's remote support",
  "Women's support",
  "Workshop",
  "Write statement",
  "Youth mentoring",
  "Youtube engagement"
];